### ISSUE TITLE
skinned 1st person view hand

### ISSUE THREAD

**Issue by Niklp09** [MrRar/edit_skin#2]
It would be nice if the player hand gets the same skin as the rest of the player (like in SkinsDB).

https://github.com/minetest-mods/skinsdb/commit/2e39651821019260fb2a692bea92df78a5be7cf4

**Comment by MrRar** [comment]
Good idea. I might try this when I get time.

**Comment by MrRar** [comment]
I have added this feature. However it's basic because it relies on registered nodes. Nodes can only be registered at load time. There is an unlimited number of colors for the shirt part so an unlimited number of nodes would need to be registered.
For this reason only the base and base color are shown.
